#! /bin/bash

if [[ $(tail -n+3 /proc/net/wireless 2>/dev/null) ]]; then
	ssid=$(nmcli -t -f name connection show --active | head -n 1)
	wireless_icon="^c#ddb6f2^ ^d^" 
else
	wireless_icon=" "
fi

printf "$wireless_icon"
